danceapp/urls.py
from django.urls import path
from . import views

app_name = 'danceapp'

urlpatterns = [
    path('', views.IndexView.as_view(), name = 'main'),
    path('search/', views.PostSearchList.as_view(), name='search'),
    path('detail/<int:pk>/', views.PostDetail.as_view(), name='detail'),
    path('category/<int:pk>/', views.PostCategoryList.as_view(), name='category'),
    path('archive/<int:year>/', views.PostYearList.as_view(), name='year'),
    path('archive/<int:year>/<int:month>/', views.PostMonthList.as_view(), name='month'),
    #path('<int:post_id>/', views.post_detail, name="post_detail"),
]

danceproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from danceapp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('danceapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

danceapp/models.py
from django.db import models
from django.utils import timezone

class Category(models.Model):
    name = models.CharField('カテゴリ名', max_length=255)

    def __str__(self):
        return self.name

class PostQuerySet(models.QuerySet):

    def published(self):
        return self.filter(published__lte=timezone.now())

class Post(models.Model):
    title = models.CharField(max_length=100)
    published = models.DateTimeField('作成日', default=timezone.now)
    youtube = models.TextField()
    text = models.TextField()
    category = models.ForeignKey(Category, verbose_name='カテゴリ', on_delete=models.PROTECT)

    objects = PostQuerySet.as_manager()
    

    def __str__(self):
        return self.title

    def summary(self):
        return self.text[:100]

danceapp/forms.py
from django import forms
from django.core.files.storage import default_storage

class PostSearchForm(forms.Form):
    """検索フォーム。"""
    key_word = forms.CharField(
        label='検索キーワード',
        required=False,
    )

danceapp/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.list import ListView
from django.utils import timezone
from django.db.models import Q
from django.http import Http404, HttpResponseBadRequest, JsonResponse
from django.views import generic
from .forms import PostSearchForm
from .models import Post,Category

class ArchiveListMixin:
    model = Post
    paginate_by = 5
    date_field = 'published'
    template_name = 'main.html'
    allow_empty = True
    make_object_list = True

class IndexView(ArchiveListMixin, generic.ArchiveIndexView):

    def get_queryset(self):
        return super().get_queryset().select_related('category')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['heading'] = '最新の投稿'
        return context

class PostSearchList(ArchiveListMixin, generic.ArchiveIndexView):

    def get_queryset(self):
        queryset = super().get_queryset()
        self.request.form = form = PostSearchForm(self.request.GET)
        form.is_valid()
        self.key_word = key_word = form.cleaned_data['key_word']
        if key_word:
            queryset = queryset.filter(Q(title__icontains=key_word) | Q(text__icontains=key_word))
        return queryset.select_related('category')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['heading'] = '「{}」 の検索結果'.format(self.key_word)
        return context


class PostDetail(generic.DetailView):
    model = Post
    template_name = 'post_detail.html'

    def get_object(self, queryset=None):
        post = super().get_object()
        if post.published <= timezone.now():
            return post
        raise Http404

class PostCategoryList(ArchiveListMixin, generic.ArchiveIndexView):

    def get_queryset(self):
        self.category = category = get_object_or_404(Category, pk=self.kwargs['pk'])
        return super().get_queryset().filter(category=category).select_related('category')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['heading'] = '「{}」 カテゴリの投稿'.format(self.category.name)
        return context

class PostYearList(ArchiveListMixin, generic.YearArchiveView):

    def get_queryset(self):
        return super().get_queryset().select_related('category')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['heading'] = '{}年の投稿'.format(self.kwargs['year'])
        return context

class PostMonthList(ArchiveListMixin, generic.MonthArchiveView):
    month_format = '%m'

    def get_queryset(self):
        return super().get_queryset().select_related('category')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['heading'] = '{}年{}月の投稿'.format(self.kwargs['year'], self.kwargs['month'])
        return context

danceapp/templates/base.html
{% load app_tags %}
{% load static %}
<!doctype html>
<html lang="ja" >
  <head>
    <title>アツダン～熱いダンス動画で心躍る！～</title>
    <link rel="canonical" href="">
    <link rel="icon" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP&display=swap" rel="stylesheet">
    <link rel='stylesheet' type='text/css' href="{% static 'style.css' %}">
  </head>
  <body >
    <div class="container">
      {% render_category_links %}
      <div class="container"> 
        <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark" id="top">
          <h1>アツダン</h1>
          <p class="vw" >～熱いダンス動画で心躍る！～</p>
        </div>
      </div>
    </div>

<main role="main" class="container">
  <div class="row">
    <div class="col-md-8 blog-main">    
      {% block content %}
      {% endblock content %}     
    </div>

    <aside class="col-md-4 blog-sidebar">
      <div class="p-3 mb-3 bg-light rounded">
        <h4 class="font-italic">ブログについて</h4>
        <p class="mb-0">熱いダンス動画を見ると嫌なことも忘れちゃう私が個人的に<em>熱い</em>と思ったダンス動画を紹介していきます。ダンスのことが良くわからない人にも何が<em>熱い</em>のかわかるように解説することを心がけています。紹介動画を見て心踊ってもらえたら最高です！</p>
      </div>

      {% render_search_form request %}
      
      {% render_month_links %}

      <!-- <div class="p-3">
        <h4 class="font-italic">SNS</h4>
        <ol class="list-unstyled">
          <li><a href="#">Twitter</a></li>
          <li><a href="#">Facebook</a></li>
          <li><a href="#">Instagram</a></li>
        </ol>
      </div> -->
    </aside>

  </div>

</main>

<footer class="blog-footer"> 
  <p>アツダン@Namaskaar</p>
  <p>
    <a href="#">トップに戻る</a>
  </p>
</footer>
<script src="https://getbootstrap.com/docs/5.0/docs/4.5/assets/js/vendor/holder.min.js"></script>
<script>
  Holder.addTheme('thumb', {
    bg: '#55595c',
    fg: '#eceeef',
    text: 'Thumbnail'
  });
</script>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script>
  window.jQuery || document.write('<script src="/docs/4.5/assets/js/vendor/jquery-slim.min.js"><\/script>')
</script><script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script><script src="https://getbootstrap.com/docs/5.0/docs/4.5/assets/js/vendor/anchor.min.js"></script>
<script src="https://getbootstrap.com/docs/5.0/docs/4.5/assets/js/vendor/clipboard.min.js"></script>
<script src="https://getbootstrap.com/docs/5.0/docs/4.5/assets/js/vendor/bs-custom-file-input.min.js"></script>
<script src="https://getbootstrap.com/docs/5.0/docs/4.5/assets/js/src/application.js"></script>
<script src="https://getbootstrap.com/docs/5.0/docs/4.5/assets/js/src/search.js"></script>
<script src="https://getbootstrap.com/docs/5.0/docs/4.5/assets/js/src/ie-emulation-modes-warning.js"></script>
  </body>
</html>

danceapp/templates/includes/category_links.html
<div class="nav-scroller py-1 mb-2">
  <nav class="nav d-flex ">
    <a class="p-2 text-muted" href="{% url 'danceapp:main' %}">ホーム</a>
    {% for category in category_list %}
    <a class="p-2 text-muted" href= "{% url 'danceapp:category' category.pk %}">{{ category }}</a>
    {% endfor %}
  </nav>
</div>



danceapp/templates/includes/month_links.html
{% regroup dates by year as dates_by_year %}
<div class="p-3">
    <!-- <h4 class="font-italic">Archives</h4> -->
    <h4 class="font-italic">月別アーカイブ</h4>
        {% for month in dates_by_year %}
            <a href="{% url 'danceapp:year' month.grouper %}">{{ month.grouper }}年</a>
            <ul>
                {% for d in month.list %}
                <p><a href="{% url 'danceapp:month' month.grouper d.month %}">{{ d|date:'F' }}</a></p>
                {% endfor %}
            </ul>
        {% endfor %}
</div>

danceapp/templates/includes/search_form.html
<form action="{% url 'danceapp:search' %}" method="GET">
    <div class="input-group container-fluid">
        <span class="input-group-btn">
            <button class="btn btn-default p-0" type="submit">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3">
                    <circle cx="10.5" cy="10.5" r="7.5"></circle>
                    <line x1="21" y1="21" x2="15.8" y2="15.8"></line>
                </svg>
            </button>
        </span>
        {{ search_form.key_word }}
    </div>       
</form>
<hr>


danceapp/templates/main.html
{% extends 'base.html' %}
{% load app_tags %}
{% block content %}

<div class="blog-post">
  <h2>{{ heading }}</h2>
  <hr>
  {% for post in object_list|slice:"5" %}
    <h3>
      <a href = "{% url 'danceapp:detail' post.pk %}">{{ post.title }}</a>
    </h3>
    <p class="blog-post-meta">{{ post.published }}</p>
    <div class="embed-responsive embed-responsive-16by9">
      <iframe class="embed-responsive-item" src="{{ post.youtube }}" allowfullscreen></iframe>
    </div>
    {{ post.summary }}
    <br /><br />    
    <hr>
  {% endfor %}        
</div>

<nav id="page" class="blog-pagination">
      {% if page_obj.has_previous %}
        <a id="prev" class="btn btn-outline-primary" href="?{% url_replace request 'page' page_obj.previous_page_number %}" title="新しい投稿へ">新しい投稿</a>
      {% endif %}

  <span id="page-info">Page:{{ page_obj.number }} / {{ page_obj.paginator.num_pages }}</span>
      {% if page_obj.has_next %}
        <a id="next" class="btn btn-outline-primary" href="?{% url_replace request 'page' page_obj.next_page_number %}" title="古い投稿へ">古い投稿</a>
      {% endif %}
</nav>

{% endblock content %}

danceapp/templates/post_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="blog-post">
  <h2 class="blog-post-title">{{ post.title }}</h2>
  <p class="blog-post-meta">{{ post.published }}</p>
    <div class="embed-responsive embed-responsive-16by9">
      <iframe class="embed-responsive-item" src="{{ post.youtube }}" allowfullscreen></iframe>
    </div>
    {{ post.text | linebreaksbr }}
    <br /><br />
         
</div>
{% endblock content %}